### ISSUE TITLE
Review the entities for Leaderboard

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#234]
I just noticed that for leaderboard, the Nether.Data entities/contracts are used directly in the EF context for the DbSets. This is in contrast to the other features which have separate types to allow for slightly different modelling.

After a very brief look, it seems that the [GameScore](https://github.com/dx-ted-emea/nether/blob/master/src/Nether.Data/Leaderboard/GameScore.cs) might benefit from being broken out. It has Rank so that the rank can be returned from the leaderboard methods. The same type is used for saving a new score, where it doesn't make sense to accept the rank.

It may even be worth splitting out the scores concepts (add a new score, list my scores) from the leaderboard concepts (where am I on the leaderboard, who are the top players, ...)

**Comment by navalev** [comment]
@stuartleeks what are your thoughts for this issue? I believe we can close this.
