### ISSUE TITLE
Out of the box compile experience with Visual Studio 2015: TypeScript Error

### ISSUE THREAD

**Issue by krist00fer2** [MicrosoftDX/nether#241]
This error is thrown when doing an out of the box compile of Nether from within Visual Studio 2015:

Error	MSB6006	"tsc.exe" exited with code 1.	Nether.Web	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets	214	

This problem seem to be fixed (as a work around) by re-installing the TypeScript Tools for Visual Studio

**Comment by stuartleeks** [comment]
This seems to be resolved with VS 2017
