### ISSUE TITLE
Change EventProcessor to not have a hard dependency of EventHub Named "ingest"

### ISSUE THREAD

**Issue by krist00fer2** [MicrosoftDX/nether#277]
Use the techiques described here https://docs.microsoft.com/en-us/azure/app-service-web/websites-dotnet-webjobs-sdk-storage-queues-how-to#a-idsetnamesincodeaset-values-for-webjobs-sdk-constructor-parameters-in-code 

#267

**Comment by stuartleeks** [comment]
Closing as this looks like it is done as per #278, #289
