### ISSUE TITLE
Admin UI - can't update/add players and groups

### ISSUE THREAD

**Issue by ankodu** [MicrosoftDX/nether#364]
You cannot update or add either player or groups through the Admin UI. This works fine for the integrations tests. The following error occurs:

![image](https://cloud.githubusercontent.com/assets/6884103/23273954/496529da-fa01-11e6-809e-e3a9debf8498.png)

**Comment by stuartleeks** [comment]
The error in the screenshot shows an auth issue, but I've not managed to repro that.

I do get an error when I try to create a player in the adminui though:

![image](https://cloud.githubusercontent.com/assets/1824461/23282768/ab1a9e1c-fa1a-11e6-8fd5-5306bb010aea.png)


The form in the UI doesn't have userid (and indeed we don't have anywhere to create a user or get their id!), but it is a required field for the player entry:

![image](https://cloud.githubusercontent.com/assets/1824461/23282787/c875e1ce-fa1a-11e6-81cc-886a743c4a61.png)

**Comment by vflorusso** [comment]
I'll try and repro today and anyhow add the userid to the player add form

**Comment by ankodu** [comment]
We have removed the UI
