### ISSUE TITLE
Analytics - Durations.DisplayName should be Name/Identifier

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#369]
Analytics includes `Durations` which is a generic way to have game events with durations. Currently the output format includes `DisplayName`. 
[example](https://github.com/MicrosoftDX/nether/blob/87be974b71a76b0054077e9724400b8e8916f3a4/src/Nether.Analytics.HiveScripts/duration/annualdurations.hql#L5)

As I understand it, this couples the name displayed on the report to the name passed in on the event from the game. This limits localisation, changing the displayed name later, ...

I suggest changing DisplayName to Name/Identifier.

**Comment by ankodu** [comment]
@oliviak any thoughts?

**Comment by krist00fer** [comment]
We have completely new message models and they will all be described as part of the recipe they belong to. The duration-events are currently not supported, but when they will they will be documented correctly.
