### ISSUE TITLE
Analytics - how to create output SQL Schema in isolation

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#370]
We should spend some time thinking about the best way to create the SQL Schema for the output from the analytics if someone wants to use _just_ the analytics (i.e. without the API project, which is where the schema is created using EF migrations)

**Comment by stuartleeks** [comment]
Now that we're planning to put a CLI together, the migrations code can be invoked from there.

**Comment by krist00fer** [comment]
With the new recipe approach we can also use the same EF-migrations. No need to implement anything else at this point.
