### ISSUE TITLE
Overall Client SDK Requirements

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#385]
Client SDK Requirements:

- Should be simple to use
- Should have a native look and feel to the target platform
- Should look similar across different platforms
- Should or could be delivered in a way that feels natural to the target platform (i.e. Unity Package, NuGet Package, Cocoa Pod, etc.).

Required features:

- Authentication
  - SDK should have an auth method that allows you to pass the token from any authentication provider. Allows for handy starting point while building out the SDK, but also if the server adds a new auth provider then this is an escape hatch while the client SDK gets updated to support it.
  - SDK should allow developers to configure and handle authentication with Facebook and/or “guest player” (using whatever SDK that is available on the target platform for Facebook authentication)
- Generic API
  - SDK should allow developers to call the other REST APIs exposed by Nether, like Leaderboard and Player Management APIs
- Analytics
  - SDK should allow developers to send Analytics Game Events to the Analytics Building Block of Nether by hiding the fact that we query Nether API for a secure endpoint to EventHub (should include renewal of these credentials once they time out)
  - SDK should allow developer to send generic/custom messages by manually writing the message.
  - SDK should allow developers to send “known Analytics Game Event” as easy as calling a method. For example sending an event when: Game Starts, Game Ends, Heartbeat, Location, Etc.
  - SDK should allow developers to configure automatic sending of Heartbeat events every N seconds, meaning the developer should not have to care about that happening in the background.

Priority 2

- Analytics
  - SDK should allow developers to automatically send Device Capabilities, meaning the SDK should query the device it’s running on of its capabilities (like: operating system, screen size, memory usage, etc.)
  - SDK should allow developers to configure automatic sending of location events every N seconds, meaning the SDK should automatically send the Location Event with Latitude and Longitude of the player
- Authentication
  - SDK should allow developer to configure and handle authentication with secondary authentication provider (we’ve not yet decided on which one to pick as the secondary one)

**Comment by stuartleeks** [comment]
Should there be a goal of creating some similarity across the SDKs? (obviously within the confines of keeping something that is idiomatic to the SDK platform)

**Comment by stuartleeks** [comment]
And I'd add that the SDKs should have an auth method that allows you to pass the token. Firstly it's probably a handy starting point while building out the SDK, but also if the server adds a new auth provider then this is an escape hatch while the client SDK gets updated to support it :-)

**Comment by krist00fer** [comment]
@stuartleeks good comments, your suggestions are incorporated

**Comment by stuartleeks** [comment]
Just to clarify my point:
Rather than:
> SDK should have an auth method that allows you to pass the token from any authentication provider.

I would say
> SDK should have an authentication method that allows you to pass the token received from Nether Identity services

For facebook and username/password authn we should have helpers that do the necessary interaction with Nether etc and abstract away as much as possible. They then get the Nether token and pass it to this method. By exposing the method publicly, the consumer _could_ go through the process for a new auth type that the server supports by doing the new flow themsevles rather than having to wait for the SDK to be updated to include it.
