### ISSUE TITLE
load test: stopping leaderboard API call causes Webapp to restart

### ISSUE THREAD

**Issue by navalev** [MicrosoftDX/nether#398]
#111 
During load testing on Free tier web app, stopping the test in the middle of API calls causes the web app to restart. assuming this is triggered from the test stopping.

**Comment by stuartleeks** [comment]
Does this happen every time the test stops?
Would be interesting to see if it happens on Basic tier?
Also, is there anything in the logs prior to shutdown?

**Comment by navalev** [comment]
Close as non-reproducible.
