### ISSUE TITLE
Update deployment to allow free SQLDB

### ISSUE THREAD

**Issue by stuartleeks** [MicrosoftDX/nether#417]
Update the deployment to allow the use of the Web App + SQL](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Microsoft.WebSiteSQLDatabase) offering with free SQLDB

**Comment by avodovnik** [comment]
I'm looking at this - should just be a _simple_ update of the nether-deploy-db.json with the correct tier specification for SQL. Right?

**Comment by stuartleeks** [comment]
Cool. Yep, that's my hope :-)

**Comment by avodovnik** [comment]
@stuartleeks should the deployment also default to the Free SKU?

**Comment by stuartleeks** [comment]
Yes, I think so for the quickstart
