### ISSUE TITLE
Get /endpoint to return object with property?

### ISSUE THREAD

**Issue by dgkanatsios** [MicrosoftDX/nether#435]
Almost all API methods return an object with a JSON property that points to a JSON object/array whereas some other methods return the entire JSON object directly.
For instance, GET /player returns 
```
{
  "player": {
    "gamertag": "string",
    "country": "string",
    "customTag": "string"
  }
}
```
However, GET /endpoint returns
```
{
  "httpVerb": "string",
  "url": "string",
  "contentType": "string",
  "authorization": "string",
  "validUntilUtc": "2017-04-16T20:46:53.271Z"
}
```
Same situation in POST /identity/connect/token.
This can make the client SDK de-serialization a bit tricky(*), should this be fixed?

(*): In Get /Player, two classes are needed; one "PlayerResult" (or something) that has a property that points to a "Player" class (with a gamertag, country and a customTag).
In Get /Endpoint, only an Endpoint class is needed

**Comment by krist00fer** [comment]
@stuartleeks hey, can you just have a look at this and give @dgkanatsios a clear to go ahead and implement it (or not)

**Comment by krist00fer** [comment]
Personally I like the more simple version implemented by the second example above.

**Comment by stuartleeks** [comment]
For API calls that return a collection I think we should keep the nested property, but I'm happy to drop the nested object in the single return value case. 

I.e. 

```json
 {
    "gamertag": "string",
    "country": "string",
    "customTag": "string"
 }
```

**Comment by dgkanatsios** [comment]
So, my main issue in the Unity SDK is that in all API calls there is a "return" object of type T (in a callback form). The JSON object is wrapped into this T object. My main issue is that right now (https://github.com/dgkanatsios/NetherUnitySDK/blob/master/Assets/NetherSDK/NetherClient.cs#L115) there is an "if" that is used to properly deserialize the object.
pseudocode
```
if the object has a "result" property
     dive into this property and deserialize what it points to
else if the object does not have a "result" property
    just deserialize the entire object
```

The "dive into this property" currently involves Reflection which I'd like to avoid. Bottom line, the request is purely for a single JSON representation (either with a property or without it).
