### ISSUE TITLE
CodeFormatter requires Visual Studio 2015 

### ISSUE THREAD

**Issue by navalev** [MicrosoftDX/nether#451]
https://github.com/dotnet/codeformatter 
Nether requires Visual Studio 2017. Currently requires installing 2015 alongside to allow codeformatter review.

**Comment by stuartleeks** [comment]
See https://github.com/dotnet/codeformatter/issues/199

**Comment by stuartleeks** [comment]
I made a custom build of CodeFormatter using VS2017 and targetting .NET 4.6, and @krist00fer tested this and reported it working. I will package that somewhere accessible and then temporarily update the RunCodeFormatter.ps1 script to use that version. Once CodeFormatter has a release that supports .NET 4.6 we can revert the script to the official release location.

**Comment by stuartleeks** [comment]
#454 contains a change to use the custom build (hosted on Azure Storage).

If you already have CodeFormatter downloaded (i.e. you have previously run RunCodeFormatter.ps1) then run `RunCodeFormatter.ps1 -ForceCodeFormatterDownload` once to download the updated build
