### ISSUE TITLE
Classes should not output to Console by default but rather use a logging infrastructure

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#463]
No library class should output to the console by default. We should come up with a standard way of writing to logs that we implement and use all over Nether.

**Comment by stuartleeks** [comment]
I imagined that we'd leverage something like the [.NET Core logging framework](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

**Comment by CarlosSardo** [comment]
The ASP.NET Core Logging framework is now also being used in the Nether.Analytics solution.
Basically, all the classes that are Program(XX).cs (console apps) where Console.WriteLine was being used, where replace with the _logger.LogInformation/LogError/LogWarning. By default, it outputs to trace and  console output window. So you'll be able to see the logs as usual.

In the future, I recommend creating a new feature where you can also enable log outputs to Azure App Insights: https://github.com/Microsoft/ApplicationInsights-aspnetcore/wiki/Getting-Started
