### ISSUE TITLE
FileOutputManager

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#475]
FileOutputManager should be responsible for writing messages to file system files. This should be very similar to the DataLakeStoreOutputManager so that should be seen as a template.

The reasons we want this output manager is that we can use it to provide accurate local data files to use when we want to execute ADLA queries locally. Today you would have to create the input files manually or create them in DataLakeStore and then download them. Having a FileOutputManager would make the development story for Nether much easier and faster.

**Comment by navalev** [comment]
implemented in #507. Please close.
