### ISSUE TITLE
CosmosOutputManager

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#477]
CosmosOutputManager is responsible for writing serialized messages to Cosmos DB, something that could be used for later consumtion from witin PowerBI. This output manager shares some similarities to other OutputManagers but since we are outputting to a database rather than a filesystem/blobstorage, it might differ some. Make sure to synchronize with and be influenced by other OutputManagers, especially any other database output managers.

**Comment by avodovnik** [comment]
Nava suggested we have the partition key as the constructor option for the OutputManager, which makes sense. The partitioning will be based on _dynamic_ properties of the message, so this will mean it'll take some CPU time to find the message each time, but it's probably a better way of doing it than trying to change the Message object to contain a partition key.
