### ISSUE TITLE
SqlDatabaseOutputManager

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#480]
SqlDatabaseOutputManager is responsible for writing serialized messages to SQL Database, something that could be used for later consumtion from witin PowerBI. This output manager shares some similarities to other OutputManagers but since we are outputting to a database rather than a filesystem/blobstorage, it might differ some. Make sure to synchronize with and be influenced by other OutputManagers, especially any other database output managers.

**Comment by krist00fer** [comment]
@navalev how is this work going? Do you need help with this?

**Comment by navalev** [comment]
@krist00fer works was on hold, will resume this week. will update on any help needed
