### ISSUE TITLE
Result API

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#493]
Some of the results that are calculated should be visualized and other should be read by a computer. We need to create a set of APIs that developers can use to consume the result of the jobs that has run.

This objective is related to the creation of message readers, specified in other "issues" so make sure to synchronize work with any development done there.

In the end we want to be able to write code like the following...

```CSharp
var reader = ResultReader
{
  MessageReader = new DataLakeStoreMessageReader(...),
  ... // Any other configuration needed
};

var latest = reader.GetLatestResult();
var result = reader.GetResult(from: fromDate, to: toDate):

```

Make sure to think about edge cases, like if files or resources doesn't exist, etc.

**Comment by avodovnik** [comment]
Notes:

* Results should be IEnumerable<Message>
* Test client should work
* Assume we'll have only one reader for now (i.e. Data Lake Store)

**Comment by avodovnik** [comment]
We need results from an arbitrary file, and the "Last" result.
