### ISSUE TITLE
Deploying Nether Analytics with Service Fabric

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#498]
Not all people want to deploy using the standard "quick start template". This "issue" describes the need for us to document and automate other scenarios that goes outside of the standard way of deploying Nether.

* Test and document manual deployment of Nether Analytics in a service fabric cluster
* Automate as much as possible in order to achieve another "out of the box experience" for Nether Analytics in Service Fabric

**Comment by Annonator** [comment]
Is this one done or do we need to do additional work here? See: https://github.com/MicrosoftDX/nether.samples/pull/2
