### ISSUE TITLE
Daily Active Users Recipe

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#500]
Document all steps neede in how to achieve the endgoal:

* How many people are using my game per day

Follow the documentation template for how recipes should be written. If the template isn't good enough, then change it to a better solution and make sure to sync with any other recipes that are written or about to be written.

**Comment by krist00fer** [comment]
Make sure you two sync on this @amynic & @oliviak :-)

**Comment by amynic** [comment]
@krist00fer - we are :) probably going to try to build on what Olivia has with Hive queries but figure out if Azure Data Lake Analytics is the right tool for an easier implementation

**Comment by amynic** [comment]
PR submitted with script and recipe complete

**Comment by amynic** [comment]
PR updated with documentation changes
