### ISSUE TITLE
Running the AnalyticsTestClient without a connection string causes an exception

### ISSUE THREAD

**Issue by avodovnik** [MicrosoftDX/nether#504]
When you run the AnalyticsTestClient, without setting any connection strings, you get a NullReferenceException:

ConsoleEx.WriteConnectionString(ConfigCache.EventHubConnectionString, 4);

**Comment by avodovnik** [comment]
Quick thoughts, @krist00fer or @stuartleeks - should this output an error message, or a blank string, or still throw an exception, but a useful one?

**Comment by krist00fer** [comment]
@avodovnik what connectionstring are we talking about? There are checks as you start the AnalyticsTestClient that checks for required configuration, perhaps we just missed some.
