### ISSUE TITLE
Automate the Azure AD + Azure DLS configuration using Azure CLI 2.0

### ISSUE THREAD

**Issue by CarlosSardo** [MicrosoftDX/nether#519]
As a developer, I would enjoy having a simple "one-click" deploy and config experience. In particular, when it comes to Azure AD configurations (in this case with Data Lake Store).

As of now, only the Azure AD commands are in place.

**Comment by CarlosSardo** [comment]
Azure CLI commands reference docs:

- Azure Active Directory: https://docs.microsoft.com/en-us/cli/azure/ad
- Azure Data Lake Store: https://docs.microsoft.com/en-us/cli/azure/dls

Commands and manual steps:

1) Login and use your Azure internal subscription
_az login_
(you will be prompted to use your browser + activation code to complete the sign-in process)

2) Create a new AAD App
_az ad app create --display-name "Nether ADLS" --homepage "https://localhost:5000" --identifier-uris "https://netheradls.localhost:5000" --key-type Password --key-usage Verify --password "1q2w3e4r5t6y_"_

3) In the Azure Portal, navigate to your ADLS and add click Access Control (AIM) tab
3.1) Add a new user (your email) and choose the permissions level that suit you best (ie: Owner)

**Comment by krist00fer** [comment]
@CarlosSardo how can we automate step 3 above? We want that to be part of a single script and/or documentation
