### ISSUE TITLE
Code Formatter blocks usage of some valid C#

### ISSUE THREAD

**Issue by krist00fer** [MicrosoftDX/nether#530]
Use this issue to track any problems you come across using CodeFormatter. We can then discuss whether we think we should do something about it, remove it or replace it.

**Comment by krist00fer** [comment]
Not supported, by CodeFormatter. Messes up things below.

```cs
public static IConfigurationRoot Root
{
    get => s_root;
}

// whatever is here will be messed up
```

**Comment by krist00fer** [comment]
Not supported, by CodeFormatter. The new Tuple format

```cs
(int count, double sum) SumAndCount(IEnumerable<double> values)
{
    var count = 0;
    var sum = 0d;

    foreach (var d in values)
    {
        count++;
        sum += d;
    }
    return (count, sum);
}
```

**Comment by stuartleeks** [comment]
Thanks @krist00fer. IIRC the new property syntax results in messed up formatting, and the tuple syntax ends up with invalid code - is that correct?

**Comment by krist00fer** [comment]
For both C#7 Tuples and Property syntax, CodeFormatter, leaves the code in a shape where it no longer compiles.
